Slovenian
Crizz0/phpbb-ext-maxwidth-switch pull request #12
Opened 2022-05-02 11:52 UTC by max-ima

Slovenian translation

2022-05-02 11:55 UTC, Crizz0 requested changes

2022-05-02 11:55 UTC, Crizz0 commented on language/sl/ucp.php
> +* @package phpBB Extension - Crizzo Max-width switch - English
I thought this is the slovenian version from 2022. Please update.

2022-05-03 06:11 UTC, max-ima commented
This is the latest version of translation 1.1.0. But where can I get a newer version then.

2022-05-03 07:10 UTC, Crizz0 commented
You just need to Update the Header of your file. Nothing more. 😀

2022-05-03 21:24 UTC, Crizz0 commented on language/sl/ucp.php
> +* @package phpBB Extension - Crizzo Max-width switch - English
```suggestion
* @package phpBB Extension - Crizzo Max-width switch - Slovenia
```

2022-05-03 21:25 UTC, Crizz0 commented on language/sl/ucp.php
> +* @copyright (c) 2014 Crizzo - www.crizzo.de
```suggestion
* @copyright (c) 2022 Crizzo - www.crizzo.de
```

2022-05-05 07:35 UTC, max-ima commented
Updated

2023-12-31 13:48 UTC, closed without merging